version: '3'

services:
  coreset:
    command: python ./src/main.py
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes: 
      - ./:/workspace/coreset:rw
    build:
      context: .
